server:
  port: 8085

spring:
  profiles:
    active: ${env:dev}
  application:
    name: xsp-amazon-backend
  datasource: # 数据库连接池属性
    driver-class-name: com.mysql.jdbc.Driver # 驱动类
    url: jdbc:mysql://10.211.55.5:3306/mybatis_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8 # jdbc访问地址
    username: root # 用户名
    password: 123456 # 密码
    hikari:
      auto-commit: true # 自动提交
      maximum-pool-size: 100 # 连接池中可同时连接的最大连接数
      minimum-idle: 5 # 最小空闲连接数，为了避免后期不停的创建连接，一般与maximumPoolSize值相同
      idle-timeout: 30000 # 空闲超时时间（毫秒）只有在minimumIdle<maximumPoolSize时候生效，超时的可能被回收，数值0表示空闲连接永不回收
      max-lifetime: 1800000 # 连接池中的连接的最长生命周期（毫秒），此参数必须小于数据库连接的最大空闲时间（time_wait），数值0表示不限制
      connection-timeout: 30000 # 连接超时时间（毫秒）
      pool-name: AmazonHikariPool
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.xsp.amazon.backend.pojo
  mapper-locations: classpath:/mappers/*Mapper.xml

app:
  id: xsp-amazon
apollo:
  bootstrap:
    enabled: true  # 是否开启Applo
    namespaces: application,exception # 设置Namespace, 优先级从左到右
    eagerLoad:
      enabled: true # 将Apollo加载提到初始化日志系统之前
